apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dafolo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dafolo
  project: default
  source:
    path: dafolo/
    repoURL: https://github.com/RasmusLynge/argoCD.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
